dataset :
  train : /home/ptn/Storage/FFESNet/data/CVC-ClinicDB_Splited/trainSplited
  valid : /home/ptn/Storage/FFESNet/data/CVC-ClinicDB_Splited/validationSplited
  test  : /home/ptn/Storage/FFESNet/data/CVC-ClinicDB_Splited/testSplited

model:
  model_type  : 'B4'
  model_arch  : 'FFESNet_LE_A2FPN'
  model_name  : 'FFESNet_LE_A2FPN_B4_drop0.2_CVC-ClinicDB'

hyparameters:
  init_trainsize  : 384
  batch_size      : 16
  repeats         : 1
  n_epochs        : 100
  learning_rate   : 0.0001
  drop_rate       : 0.2