dataset :
  train : /home/ptn/Storage/FFESNet/data/TrainDataset/Mix-Kvasir-ClinicDB
  valid : /home/ptn/Storage/FFESNet/data/TestDataset
  test  : /home/ptn/Storage/FFESNet/data/TestDataset

model:
  model_type  : 'B2'
  model_arch  : 'FFESNet_PAN'
  model_name  : 'FFESNet_PAN_B2_drop0.2_Kvasir'

hyparameters:
  init_trainsize  : 384
  batch_size      : 32
  repeats         : 2
  n_epochs        : 100
  learning_rate   : 0.0001
  drop_rate       : 0.2