dataset :
  train : /home/ptn/Storage/FFESNet/data/TrainDataset/Mix-Kvasir-ClinicDB
  valid : /home/ptn/Storage/FFESNet/data/TestDataset
  test  : /home/ptn/Storage/FFESNet/data/TestDataset

model:
  model_type  : 'B4'
  model_arch  : 'FFESNet_LE_A2FPN'
  model_name  : 'FFESNet_LE_A2FPN_B4_drop0.5_Kvasir'

hyparameters:
  init_trainsize  : 384
  batch_size      : 16
  repeats         : 2
  n_epochs        : 100
  learning_rate   : 0.0001
  drop_rate       : 0.5